apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cicd
  labels:
    app: demo-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-cicd
  template:
    metadata:
      labels:
        app: demo-cicd
    spec:
      containers:
      - name: demo-cicd
        image: demo-cicd:latest
        imagePullPolicy: Never  # Use local image for kind
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
