apiVersion: v1
kind: Service
metadata:
  name: demo-cicd-service
  labels:
    app: demo-cicd
spec:
  type: NodePort
  selector:
    app: demo-cicd
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080  # Access via http://localhost:30080
    protocol: TCP
    name: http
